### ISSUE TITLE
jre-8u121-linux-x64.rpm Error 404 not found

### ISSUE THREAD

**Issue by rblaine95** [andrewrothstein/ansible-zookeeper-cluster#1]
When deploying a Zookeeper Cluster, the deployment fails when downloading `jre-8u121-linux-x64.rpm`
When following the link below, then I get an unauthorized request page from Oracle.

```
TASK [andrewrothstein.java-oracle-jre : download rpm] **************************
fatal: [zk01]: FAILED! => {"changed": false, "dest": "/tmp/jre-8u121-linux-x64.rpm", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jre-8u121-linux-x64.rpm"}
```

**Comment by andrewrothstein** [comment]
I upgrade the andrewrothstein.zookeeper role to pick up the latest version of the Oracle JRE and revved this role to upgrade its dependencies. A fixed version is published to the hub as andrewrothstein.zookeeper-cluster v2.0.3.
