### ISSUE TITLE
zkServer.sh: line 170: exec: java: not found

### ISSUE THREAD

**Issue by rblaine95** [andrewrothstein/ansible-zookeeper-cluster#2]
I keep getting this error on the Zookeeper nodes when checking `journalctl -u zookeeper -f`
```
Jun 09 09:26:40 zk-1 zkServer.sh[2200]: ZooKeeper JMX enabled by default
Jun 09 09:26:40 zk-1 zkServer.sh[2200]: Using config: /usr/local/zookeeper/bin/../conf/zoo.cfg
Jun 09 09:26:40 zk-1 zkServer.sh[2200]: /usr/local/zookeeper/bin/zkServer.sh: line 170: exec: java: not found
Jun 09 09:26:40 zk-1 systemd[1]: zookeeper.service: main process exited, code=exited, status=127/n/a
Jun 09 09:26:40 zk-1 systemd[1]: Unit zookeeper.service entered failed state.
Jun 09 09:26:40 zk-1 systemd[1]: zookeeper.service failed.
```
Line 170-171 of zkServer.sh:
```
    "${ZOO_CMD[@]}" "-Dzookeeper.log.dir=${ZOO_LOG_DIR}" "-Dzookeeper.root.logger=${ZOO_LOG4J_PROP}" \
    -cp "$CLASSPATH" $JVMFLAGS $ZOOMAIN "$ZOOCFG"
```

And I'm getting a very similar error with Kafka when checking `journalctl -u kafka -f`

```
Jun 09 09:27:37 kn-1 systemd[1]: Starting Apache Kafka Broker...
Jun 09 09:27:37 kn-1 systemd[1]: Started Apache Kafka Broker.
Jun 09 09:27:37 kn-1 kafka-server-start.sh[14590]: /usr/local/kafka/bin/kafka-run-class.sh: line 258: exec: java: not found
Jun 09 09:27:37 kn-1 systemd[1]: kafka.service: main process exited, code=exited, status=127/n/a
Jun 09 09:27:37 kn-1 systemd[1]: Unit kafka.service entered failed state.
Jun 09 09:27:37 kn-1 systemd[1]: kafka.service failed.
```
Line 254-259 of kafka-run-class.sh
```
# Launch mode
if [ "x$DAEMON_MODE" = "xtrue" ]; then
  nohup $JAVA $KAFKA_HEAP_OPTS $KAFKA_JVM_PERFORMANCE_OPTS $KAFKA_GC_LOG_OPTS $KAFKA_JMX_OPTS $KAFKA_LOG4J_OPTS -cp $CLASSPATH $KAFKA_OPTS "$@" > "$CONSOLE_OUTPUT_FILE" 2>&1 < /dev/null &
else
  exec $JAVA $KAFKA_HEAP_OPTS $KAFKA_JVM_PERFORMANCE_OPTS $KAFKA_GC_LOG_OPTS $KAFKA_JMX_OPTS $KAFKA_LOG4J_OPTS -cp $CLASSPATH $KAFKA_OPTS "$@"
fi
```

This error only comes up when kafka and zookeeper are run as **services**.
If I **manually** execute the kafka and zookeeper start scripts, then the error doesn't exist.
`/usr/local/zookeeper/bin/zkServer.sh start-foreground`  
`/usr/local/kafka/bin/kafka-server-start.sh /usr/local/kafka/config/server.properties`

When deploying the Zookeeper/Kafka Cluster on fresh nodes, the environment variables `JAVA_HOME` and `JRE_HOME` don't exist and manually executing the start scripts for Zookeeper and Kafka causes the `line 170` and `line 258` not found errors.
However, rebooting the nodes or reloading the bash profile, then **manually** executing the start scripts, fixes the error. Starting the Zookeeper or Kafka services still has the error.

It seems that the environment variables don't take effect without having to reboot the nodes.
Even after rebooting the nodes, the services aren't able to access the environment variables, even though everything is being run via `root`.

The nodes are running CentOS7 on a Digital Ocean cluster being deployed via Terraform with Ansible Playbook provisioning the cluster.

**Comment by RBlaine95** [comment]
Temporary fix found:

In the `zookeeper.service.j2` and `kafka.service.j2` templates if you add the Environment Variable Declarations under the `[service]` tag, it will solve this problem.

```
[Unit]
Description=Apache Kafka Broker
Documentation=http://kafka.apache.org/documentation.html
Requires=network.target
After=network.target

[Service]
Type=simple
ExecStartPre=-/usr/bin/mkdir -p {{kafka_log_dirs}}

Environment=JAVA_HOME=/usr/local/java
Environment=JRE_HOME=/usr/local/java

ExecStart={{kafka_dir}}/bin/kafka-server-start.sh {{kafka_dir}}/config/server.properties
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by rblaine95** [comment]
Temporary fix found:

In the `zookeeper.service.j2` and `kafka.service.j2` templates if you add the Environment Variable Declarations under the `[service]` tag, it will solve this problem.

Example with the `kafka.service.j2` template:
```
[Unit]
Description=Apache Kafka Broker
Documentation=http://kafka.apache.org/documentation.html
Requires=network.target
After=network.target

[Service]
Type=simple
ExecStartPre=-/usr/bin/mkdir -p {{kafka_log_dirs}}

Environment=JAVA_HOME=/usr/local/java
Environment=JRE_HOME=/usr/local/java

ExecStart={{kafka_dir}}/bin/kafka-server-start.sh {{kafka_dir}}/config/server.properties
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by andrewrothstein** [comment]
Many of my roles suffer from this. Apologies. I'm going to update the java-jre/java-jdk roles to write an environment file that can be specified in these systemd service definitions.

**Comment by andrewrothstein** [comment]
can you try again with v2.0.4 of this role?

**Comment by rblaine95** [comment]
Can I just update by reinstalling it with `ansible-galaxy install andrewrothstein.zookeeper-cluster`?

**Comment by rblaine95** [comment]
It still gives the error when using the latest version.

**Comment by andrewrothstein** [comment]
There was a bug that I just patched over. Do an ```ansible-galaxy install -f andrewrothstein.zookeeper-cluster``` and try again please?

**Comment by rblaine95** [comment]
Yes! It is working perfectly now!

**Comment by rblaine95** [comment]
Alright, the Zookeeper-Cluster works perfectly, Kafka is still broken though.

**Comment by andrewrothstein** [comment]
I similarly fixed the andrewrothstein.kafka-broker v2.0.3 role. Can you please try upgrading that role to the latest?

**Comment by rblaine95** [comment]
Just deployed, Kafka and Zookeeper are working perfectly.
Going to test with a completely fresh deployment, will update as soon as that finishes.

**Comment by rblaine95** [comment]
Alright, just did a clean deployment, Zookeeper and Kafka starts up perfectly.
The problem now is that when trying to Produce and Consume messages (creating a topic, describe the topic, produce messages, consume the messages, etc) Kafka claims the scripts `kafka-topics.sh`, `kafka-console-producer.sh`, etc are not found. Fix is to reload the bash shell `bash -l` or to reboot the nodes.

**Comment by andrewrothstein** [comment]
my roles install shell scriptlets in /etc/profile.d reflecting the configuration. you've always needed a login shell to get those environment variables in your shell environment.

in separate but related news I have two other roles that I was using to test kafka out. andrewrothstein.kafka-producer and andrewrothstein.kafka-consumer. They might be of interest to you.

thanks for bringing these issues to my attention! I'm glad you find these roles useful!

**Comment by taverentech** [comment]
If you got this error after uninstalling oracle java and replacing it with open-jd, the PROPER fix is to purge oracle pkgs rather than just remove, or manually remove the files under /etc/profile.d for jdk.sh that oracle java installed which sets JAVA_HOME.

If JAVA_HOME is NOT set, then kafka class shell script will use /bin/java or /usr/bin/java which your operating system should have pointed to correct installation.

For example, on Ubuntu just uninstalling oracle java will leave these files around messing up your environment:
$ sudo find /etc -type f -exec grep JAVA_HOME {} \; -print
setenv JAVA_HOME /usr/lib/jvm/java-8-oracle
/etc/profile.d/jdk.csh
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
/etc/profile.d/jdk.sh

You have to PURGE oracle java pkgs, or remove those files in /etc/profile.d that have wrong path.

You DO NOT need to set JAVA_HOME for daemon and should avoid so to avoid future inconsistencies as long as you properly set default java:
update-java-alternatives -s java-1.8.0-openjdk-amd64
(for example)
